### PR TITLE
fix: misspell of cloudflare

### PR DESCRIPTION
**Pull request by chriscn**

### CODE REVIEW

**Review by Jbithell — APPROVED** [review]

**Comment by Jbithell** [comment]
@chriscn  did you have to fork to submit this PR - did your permissions not let you edit a branch on this repo?

**Comment by chriscn** [comment]
> @chriscn  did you have to fork to submit this PR - did your permissions not let you edit a branch on this repo?

@Jbithell I'm not a 'senior-maintainer' and hence don't have access to the main branch.

**Comment by Jbithell** [comment]
> > @chriscn  did you have to fork to submit this PR - did your permissions not let you edit a branch on this repo?
> 
> @Jbithell I'm not a 'senior-maintainer' and hence don't have access to the main branch.

Nobody has access to the main branch because branch protection is on (well technically I do as an admin but I try to be good and not use the override!) but you should be able to create branches and edit them, to then create PRs. Does this work for you?

**Comment by chriscn** [comment]
> > > @chriscn  did you have to fork to submit this PR - did your permissions not let you edit a branch on this repo?
> > 
> > 
> > @Jbithell I'm not a 'senior-maintainer' and hence don't have access to the main branch.
> 
> Nobody has access to the main branch because branch protection is on (well technically I do as an admin but I try to be good and not use the override!) but you should be able to create branches and edit them, to then create PRs. Does this work for you?

I do have access to other branches, I must have just clicked make a fork when I used GitHub's editor. Normally I would do this from the command line but didn't want to for the sake of one file. I've managed to push the branch `test-perms` so all should be good. 

I thought it was due to the `CODEOWNERS` file but seemingly that doesn't make any kind of difference.

**Comment by Jbithell** [comment]
No probs at all - just wanted to double check it had been setup correctly
in the migration to allow you to collaborate on all the other branches.
CODEOWNERS just helps apply the branch protection to confirm who needs to
approve a PR to merge into main

**Pull request merged**
